services:
  - type: web
    name: openai-proxy
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 4000 